# Generated by Django 4.1.3 on 2022-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medisep_insurance',
            name='Insurance_PaymentAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medisep_insurance',
            name='Insurance_amount',
            field=models.IntegerField(),
        ),
    ]
