# Generated by Django 4.1.3 on 2022-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_medisep_insurance_insurance_paymentamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medisep_insurance',
            name='Insurance_PaymentAmount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medisep_insurance',
            name='Insurance_amount',
            field=models.CharField(max_length=50),
        ),
    ]
