# Generated by Django 4.1.3 on 2022-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_medisep_insurance_insurance_paymentamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_registration',
            name='emp_sts',
            field=models.IntegerField(default=0),
        ),
    ]
