# Generated by Django 4.1.2 on 2022-10-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEM_REGISTRATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_name', models.CharField(max_length=50)),
                ('Mem_address', models.TextField(null=True)),
                ('Mem_contact', models.CharField(max_length=50)),
                ('Mem_emailid', models.EmailField(max_length=254, unique=True)),
                ('Mem_gender', models.CharField(max_length=50)),
                ('Mem_age', models.CharField(max_length=50)),
                ('Mem_photo', models.FileField(upload_to='MemberDocs/')),
                ('Mem_password', models.CharField(max_length=50, unique=True)),
                ('Patient_op', models.CharField(max_length=50)),
                ('Mem_doj', models.DateField(auto_now_add=True)),
                ('Emp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.emp_registration')),
                ('Mem_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
