# Generated by Django 4.1.2 on 2022-10-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenarateToken',
            new_name='Token',
        ),
    ]
