# Generated by Django 4.1.2 on 2022-10-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0002_rename_genaratetoken_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Doc_Token',
        ),
    ]
