# Generated by Django 4.1.2 on 2022-10-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOCTOR_REGISTRATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Doctor_address', models.TextField(null=True)),
                ('Doctor_contact', models.CharField(max_length=50)),
                ('Doctor_emailid', models.EmailField(max_length=254, unique=True)),
                ('Doctor_gender', models.CharField(max_length=50)),
                ('Doctor_age', models.CharField(max_length=50)),
                ('Doctor_photo', models.FileField(upload_to='MemberDocs/')),
                ('Doctor_qualification', models.CharField(max_length=50)),
                ('Doctor_password', models.CharField(max_length=50, unique=True)),
                ('Doctor_isactive', models.CharField(max_length=50, null=True)),
                ('Doctor_doj', models.DateField(auto_now_add=True)),
                ('Doctor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.dr_department')),
                ('Doctor_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.hos_registration')),
                ('Doctor_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
        migrations.CreateModel(
            name='CONSULTANCY_REGISTRATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consultancy_name', models.CharField(max_length=50)),
                ('Consultancy_head', models.CharField(max_length=50)),
                ('Consultancy_logo', models.FileField(upload_to='ConsultancyDocs/')),
                ('Consultancy_pswd', models.CharField(max_length=50, unique=True)),
                ('Consultancy_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.hos_registration')),
            ],
        ),
    ]
