# Generated by Django 4.1.2 on 2022-11-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0005_medicinereport'),
        ('Hospital', '0001_initial'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_PEno', models.CharField(max_length=50)),
                ('claim_amount', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('consultancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.consultancy_registration')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.medicinereport')),
            ],
        ),
    ]
