# Generated by Django 4.1.2 on 2022-10-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckUp_Details',
        ),
    ]
