# Generated by Django 4.1.2 on 2022-11-01 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Doctors', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup_details',
            name='checkd_bookingdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkup_details',
            name='checkd_reply',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='checkup_details',
            name='checkd_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkup_details',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Employee.mem_registration'),
            preserve_default=False,
        ),
    ]
