# Generated by Django 4.1.2 on 2022-11-01 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_checkup_details_checkd_bookingdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_title', models.CharField(max_length=50)),
                ('medicine_remark', models.TextField(null=True)),
                ('medicine', models.CharField(max_length=100)),
                ('is_major', models.CharField(max_length=50)),
                ('major_details', models.TextField(null=True)),
                ('medicine_report', models.FileField(upload_to='MedicineReport/')),
                ('checkdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.checkup_details')),
            ],
        ),
    ]
