# Generated by Django 4.1.3 on 2022-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0005_medicinereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereport',
            name='med_sts',
            field=models.IntegerField(default=0),
        ),
    ]
